### ISSUE TITLE
A link missing

### ISSUE THREAD

**Issue by nonopolarity** [wsvincent/wsvincent#1]
Sorry, trying to reach you but not sure if this is the website's repo.

On 

https://overreacted.io/a-complete-guide-to-useeffect/

There is a link 

 the canonical wrong-value-in-a-timeout confusion

to 

https://wsvincent.com/javascript-closure-settimeout-for-loop/

but it is a 404... is it just renamed or deleted?

If it is deleted can you tell us what it was about so maybe we can add a small page somewhere to let the reader know what it is about?

**Comment by wsvincent** [comment]
Hi, I removed that post cause there were so many comments about it and I didn't have the time/inclination to dive into it all. Same goes for most of my other JavaScript posts actually.
